version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: bootstrap
    versions:
    - ">= 4.a, < 5"
  - dependency-name: bootswatch
    versions:
    - ">= 4.a, < 5"
